export const books = [
  {
    src: 'assets/images/1.jpg',
    author: 'Александр Дюма',
    title: 'Граф Монте-Кристо',
    year: 1844,
    price: 1500,
    rating: 9.5,
  },
  {
    src: 'assets/images/2.jpg',
    author: 'Джордж Оруэлл',
    title: '1984',
    year: 1949,
    price: 1200,
    rating: 9.2,
  },
  {
    src: 'assets/images/3.jpg',
    author: 'Джейн Остин',
    title: 'Гордость и предубеждение',
    year: 1813,
    price: 1000,
    rating: 9.7,
  },
  {
    src: 'assets/images/4.jpg',
    author: 'Федор Достоевский',
    title: 'Преступление и наказание',
    year: 1866,
    price: 1300,
    rating: 9.8,
  },
  {
    src: 'assets/images/5.jpg',
    author: 'Лев Толстой',
    title: 'Война и мир',
    year: 1869,
    price: 1800,
    rating: 9.6,
  },
  {
    src: 'assets/images/6.jpg',
    author: 'Мигель де Сервантес',
    title: 'Дон Кихот',
    year: 1605,
    price: 1700,
    rating: 9.4,
  },
];
